spring:
  application:
    name: learnSpring

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:/Users/arban/OneDrive/Desktop/springdb
    username: anurag
    password: anurag123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
